<?php

declare(strict_types=1);

namespace RRZE\Answers\Common;

defined('ABSPATH') || exit;

/**
 * Defines the HTML policies required by RRZE Answers.
 *
 * The global WordPress post policy is extended only for the legacy inline
 * placeholder element because that element is stored in post content. Markup
 * generated by the plugin is handled by a local policy at its output boundary.
 */
final class HtmlSanitizer
{
    /** @var array<string, bool> */
    private const LEGACY_PLACEHOLDER_ATTRIBUTES = [
        'class' => true,
        'title' => true,
        'lang' => true,
        'data-placeholder-id' => true,
        'data-placeholder-title' => true,
    ];

    /** @var list<string> */
    private const MICRODATA_ELEMENTS = [
        'div',
        'span',
        'h1',
        'h2',
        'h3',
        'h4',
        'h5',
        'h6',
        'summary',
    ];

    /** @var array<string, bool> */
    private const MICRODATA_ATTRIBUTES = [
        'itemscope' => true,
        'itemtype' => true,
        'itemprop' => true,
    ];

    /** @var array<string, bool> */
    private const SELECT_ATTRIBUTES = [
        'name' => true,
        'id' => true,
        'class' => true,
        'multiple' => true,
        'size' => true,
    ];

    /** @var array<string, bool> */
    private const OPTION_ATTRIBUTES = [
        'value' => true,
        'selected' => true,
    ];

    /** @var array<string, bool> */
    private const INPUT_ATTRIBUTES = [
        'type' => true,
        'name' => true,
        'id' => true,
        'class' => true,
        'value' => true,
        'synonym' => true,
        'checked' => true,
        'disabled' => true,
        'readonly' => true,
        'maxlength' => true,
        'size' => true,
        'min' => true,
        'max' => true,
        'step' => true,
        'autocomplete' => true,
        'data-minlen' => true,
    ];

    /**
     * Preserve inline placeholders when WordPress sanitizes stored post content.
     *
     * This is intentionally the only plugin rule added to the global `post`
     * context. Existing content uses a custom `<placeholder>` element and must
     * continue to survive updates made by users without `unfiltered_html`.
     *
     * @param array<string, array<string, bool>> $allowedHtml Current allowlist.
     * @return array<string, array<string, bool>>
     */
    public static function allowLegacyPlaceholder(array $allowedHtml, string $context): array
    {
        if ($context !== 'post') {
            return $allowedHtml;
        }

        $allowedHtml['placeholder'] = array_merge(
            $allowedHtml['placeholder'] ?? [],
            self::LEGACY_PLACEHOLDER_ATTRIBUTES
        );

        return $allowedHtml;
    }

    /**
     * Sanitize markup generated at an RRZE Answers output boundary.
     *
     * WordPress post HTML remains the baseline. Only the microdata and form
     * controls actually emitted by the plugin are added locally; notably this
     * does not add the `<form>` element to the global KSES policy.
     */
    public static function sanitizePluginMarkup(string $html): string
    {
        return (string) wp_kses($html, self::pluginMarkupAllowlist());
    }

    /**
     * Build the local allowlist for generated plugin markup.
     *
     * @return array<string, array<string, bool>>
     */
    private static function pluginMarkupAllowlist(): array
    {
        /** @var array<string, array<string, bool>> $allowedHtml */
        $allowedHtml = wp_kses_allowed_html('post');

        foreach (self::MICRODATA_ELEMENTS as $element) {
            $allowedHtml[$element] = array_merge(
                $allowedHtml[$element] ?? [],
                self::MICRODATA_ATTRIBUTES
            );
        }

        $allowedHtml['select'] = array_merge(
            $allowedHtml['select'] ?? [],
            self::SELECT_ATTRIBUTES
        );
        $allowedHtml['option'] = array_merge(
            $allowedHtml['option'] ?? [],
            self::OPTION_ATTRIBUTES
        );
        $allowedHtml['input'] = array_merge(
            $allowedHtml['input'] ?? [],
            self::INPUT_ATTRIBUTES
        );

        return $allowedHtml;
    }
}
